//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChecklistService_Helper.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChecklistService_Helper.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to insert new data, see log for more detail.
        /// </summary>
        internal static string AddNewTask_Exception {
            get {
                return ResourceManager.GetString("AddNewTask_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s an existing task with same description, please try a different one.
        /// </summary>
        internal static string AddNewTask_Validation {
            get {
                return ResourceManager.GetString("AddNewTask_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task added succesfully.
        /// </summary>
        internal static string AddNewTask_ValidOperation {
            get {
                return ResourceManager.GetString("AddNewTask_ValidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to execute your action, please try again later&quot;.
        /// </summary>
        internal static string Api_Exception {
            get {
                return ResourceManager.GetString("Api_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on API:.
        /// </summary>
        internal static string Api_ExceptionLogTitle {
            get {
                return ResourceManager.GetString("Api_ExceptionLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on CommandHandler:.
        /// </summary>
        internal static string CommandHandler_ExceptionLogTitle {
            get {
                return ResourceManager.GetString("CommandHandler_ExceptionLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to load data.
        /// </summary>
        internal static string ListTask_Exception {
            get {
                return ResourceManager.GetString("ListTask_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the actual existing tasks.
        /// </summary>
        internal static string ListTask_ValidOperation {
            get {
                return ResourceManager.GetString("ListTask_ValidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was unable to mark as done the selected task, see log for more detail.
        /// </summary>
        internal static string MarkTaskDone_Exception {
            get {
                return ResourceManager.GetString("MarkTaskDone_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There isn&apos;ta existing task with selected id, please try a valid id.
        /// </summary>
        internal static string MarkTaskDone_Validation {
            get {
                return ResourceManager.GetString("MarkTaskDone_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task marked as done succesfully.
        /// </summary>
        internal static string MarkTaskDone_ValidOperation {
            get {
                return ResourceManager.GetString("MarkTaskDone_ValidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected order by value is incorrect, please try again with a valid one.
        /// </summary>
        internal static string OrderTaskBy_Validation {
            get {
                return ResourceManager.GetString("OrderTaskBy_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on QueryHandler:.
        /// </summary>
        internal static string QueryHandler_ExceptionLogTitle {
            get {
                return ResourceManager.GetString("QueryHandler_ExceptionLogTitle", resourceCulture);
            }
        }
    }
}
